#!/bin/bash

# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2025 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

test -f .env && source $_

BOLT_ROOT=$(readlink -m "$(dirname "${BASH_SOURCE[0]}")")
TEMPLATECONF=${TEMPLATECONF:-${BOLT_ROOT}/meta-bolt/conf/templates}

if [ ! -d poky ]; then
  "${BOLT_ROOT}/repo-sync"
fi

source poky/oe-init-build-env

sed -i "s@##BOLTROOT##@${BOLT_ROOT}@g" conf/bblayers.conf

if [ ! -f conf/bolt.done ]; then
  test -n "${BOLT_DL_DIR}"     && echo "DL_DIR = \"$_\""     >> conf/local.conf
  test -n "${BOLT_SSTATE_DIR}" && echo "SSTATE_DIR = \"$_\"" >> conf/local.conf
  echo "${BOLT_ROOT}" > conf/bolt.done
fi
